version: "3.7"

services: 
    database_Ignite:
        image: postgres
        container_name: database_Ignite
        restart: always
        ports: 
            - 5432:5432
        environment: 
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=ignite 
            - POSTGRES_DB=rentx
        volumes:
            - pgdata:/data/postgres
    app:
        build: .
        container_name: rentx
        ports:
            - 3333:3333
        volumes: 
            - .:/usr/app
        links:
            - database_Ignite
        depends_on: 
            - database_Ignite

volumes: 
    pgdata:
        driver: local